variables:
  app_id: 'audiodecoder.2sf'

trigger:
  branches:
    include:
    - Piers
    - Omega
    - releases/*
  paths:
    include:
    - '*'
    exclude:
    - 'debian/*'

jobs:
  - job: Windows

    pool:
      vmImage: 'windows-2022'

    strategy:
      matrix:
  Win32:
    GENERATOR: "Visual Studio 17 2022"
    ARCHITECTURE: Win32
    CONFIGURATION: Release
  Win64:
    GENERATOR: "Visual Studio 17 2022"
    ARCHITECTURE: x64
    CONFIGURATION: Release
  ARM64:
    GENERATOR: "Visual Studio 17 2022"
    ARCHITECTURE: ARM64
    CONFIGURATION: Release
  Win32-UWP:
    GENERATOR: "Visual Studio 17 2022"
    ARCHITECTURE: Win32
    CONFIGURATION: Release
    WINSTORE: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0.22621.0
  Win64-UWP:
    GENERATOR: "Visual Studio 17 2022"
    ARCHITECTURE: x64
    CONFIGURATION: Release
    WINSTORE: -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0.22621.0
